name: flutter_web_auth_2
description: Flutter plugin for authenticating a user with a web service.
version: 2.0.3
homepage: https://github.com/ThexXTURBOXx/flutter_web_auth_2
repository: https://github.com/ThexXTURBOXx/flutter_web_auth_2
issue_tracker: https://github.com/ThexXTURBOXx/flutter_web_auth_2/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  flutter_web_auth_2_platform_interface: ^2.0.1
  flutter_web_plugins:
    sdk: flutter
  url_launcher: ^6.1.6
  win32: ">=2.7.0 <4.0.0"

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.linusu.flutter_web_auth_2
        pluginClass: FlutterWebAuth2Plugin
      ios:
        pluginClass: FlutterWebAuth2Plugin
      macos:
        pluginClass: FlutterWebAuth2Plugin
      web:
        pluginClass: FlutterWebAuth2WebPlugin
        fileName: src/flutter_web_auth_2_web.dart
      windows:
        dartPluginClass: FlutterWebAuth2WindowsPlugin
        pluginClass: none
